Add script to update manifest template

diff --git a/.bluemix/manifest.yml b/.bluemix/manifest.yml
--- a/.bluemix/manifest.yml
+++ b/.bluemix/manifest.yml
@@ -61,7 +61,7 @@ stages:
     type: builder
     artifact_dir: ''
     build_type: shell
-    script: |
+    script: |-
       #!/bin/bash
 
       set -x
@@ -71,8 +71,86 @@ stages:
 
       cd manifest
       make generate
+  - name: Create and register manifest
+    type: builder
+    artifact_dir: ''
+    build_type: shell
+    script: |-
+      #!/bin/bash
 
-      # Add the template
-      git add res/servicemanifest.json
-      git commit -m "Adding generated Service Manifest Json"
+      set -x
+
+      rootdir=${PWD}
+      manifestdir=manifest/res
+      manifest_template=servicemanifest.json
+
+      cd ${manifestdir}
+      node > out_${manifest_template} <<EOF
+
+      // Read data
+      var manifest = require('./${manifest_template}');
+
+      // Edit the required fields
+      manifest.service_name = 'service-name';
+      manifest.component_name = 'component-name';
+      manifest.cname = 'cname';
+      manifest.ctype = 'ctype';
+      manifest.region = 'region splt';
+      manifest.resource_type = 'cf-application';
+      manifest.tenancy = 'tenancy';
+      manifest.pager_duty = 'escalation url';
+      manifest.team_email = 'team_email';
+      manifest.bailey_url = 'bailey-url';
+      manifest.bailey_project = 'bailey-project';
+      manifest.repo_url = 'git-repo';
+      manifest.bluemix_account = '';
+
+      // Remove invalid data
+      manifest.component_instance = '';
+      manifest.scope = '';
+      manifest.resource = '';
+      manifest.softlayer_account = '';
+      manifest.softlayer_account_api_key_id = '';
+      manifest.bluemix_account_api_key_id = '';
+      manifest.security_status_url = '';
+      manifest.static_sec_analyze_url = '';
+      manifest.customer_ticket_repo_url = '';
+      manifest.runbook_repo_url = '';
+      manifest.continuity_plan_url = '';
+
+
+      // Output data
+      console.log(JSON.stringify(manifest, null, 2));
+      EOF
+
+      # Move the file to checkin
+      mv ${manifestdir}/out_${manifest_template} ${manifestdir}/${manifest_template}
+
+      # Add the updated manifest
+      cd ${rootdir}
+      git add ${manifestdir}/servicemanifest.json
+      git commit -m "Adding Service Manifest file"
       git push origin ${RUNTIME_BRANCH}
+  - name: Register manifest
+    type: builder
+    artifact_dir: ''
+    build_type: shell
+    script: |-
+      #!/bin/bash
+
+      set -x
+
+      # Change to manifest directory
+      cd manifest
+
+      # Validate the service manifest
+      make validate || exit 1
+
+      # Cleanup possible leftovers from previous builds
+      make clean || exit 1
+
+      # Build the manifest library
+      make || exit 1
+
+      # Register/Update your service component with the Service Registry
+      make package || exit 1
